FROM node:alpine

WORKDIR "/app"

COPY package.json .

RUN npm install

# we can commment this as we have mapped pwd code to containers code or we can as it is.
COPY . . 

CMD ["npm", "run", "start"]
# EXPOSE 80