version: '3'
services: 
  web:
    # build: .
    build:
      context: . # reactproject
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
    
